### ISSUE TITLE
"BMS Energy Throughput" seems off.

### ISSUE THREAD

**Issue by Ndrinta** [nathanmarlor/foxess_modbus#299]
Hey @canton7,
may be worthwhile having a look at the scaling for BMS Energy Throughput while you're at it, I'm on version 1.5.2 at the moment.
It seems little off to me that ~700kWh have gone through my battery today!

![image](https://github.com/nathanmarlor/foxess_modbus/assets/4704172/eb71522f-8899-4613-b5ba-565b73b2a52d)

After quick inspection, seems to be a U16 starting at 11049 in my H1.

Thanks!

**Comment by canton7** [comment]
Thanks! We did originally fix the scale on this, then I seem to have reverted it https://github.com/nathanmarlor/foxess_modbus/commit/482539436f493007c704a45822733af607e1dca2.

**Comment by TonyM1958** [comment]
FWIW, I tracked this for a while and its in watts, scale : 0.001. Its supposed to be the energy counter that drives BMS Cycle Count, but it is uint16 and wraps every 65kWh, making it hard to use for anything useful.

The metric that I use that makes more sense is a template Battery Energy Total. This is the sum of Charge Energy Total and Discharge Energy Total, similar to the above, but uint32 so it does wrap,and tracks battery use since install. As BMS Cycle Count also counts from installation, it then makes sense to track Battery Energy per Cycle  by dividing Battery Energy Total by BMS Cycle Count.

**Comment by Ndrinta** [comment]
Great that will be fixed, thanks, but after seeing the discussion I believe I'll disable it at once.
I think we should close this, I'll let you the onor.
